### ISSUE TITLE
TypeError: exceptions must derive from BaseException

### ISSUE THREAD

**Issue by chleidersdorff** [Septima/qgis-qlrbrowser#78]
Here is the error message i get:

An error has occurred while executing Python code: 

TypeError: exceptions must derive from BaseException 
Traceback (most recent call last):
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\qlrbrowser.py", line 188, in settingsUpdated
    self.dockwidget.addRootPath(self.settings.value("baseDirectory"))
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\ui\dockwidget.py", line 99, in addRootPath
    fs.setRootPath(path)
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\core\filesystemmodel.py", line 27, in setRootPath
    self.update()
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\core\filesystemmodel.py", line 30, in update
    self.rootitem = FileSystemItem(self.rootpath, True, FileSystemRecursionCounter(self.settings), namingregex=self.namingregex())
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\core\filesystemmodel.py", line 78, in __init__
    self.children.append(FileSystemItem(finfo, recurse, recursion_counter, self.namingregex))
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\core\filesystemmodel.py", line 78, in __init__
    self.children.append(FileSystemItem(finfo, recurse, recursion_counter, self.namingregex))
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\core\filesystemmodel.py", line 78, in __init__
    self.children.append(FileSystemItem(finfo, recurse, recursion_counter, self.namingregex))
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\core\filesystemmodel.py", line 60, in __init__
    recursion_counter.increment()
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\core\filesystemmodel.py", line 184, in increment
    raise FileSystemRecursionException("File system is too big for this file system model", self.maxcount)
TypeError: exceptions must derive from BaseException

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.8.3-Zanzibar Zanzibar, 685d8b15d2 

Python Path:
C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:/OSGEO4~1/apps/qgis/./python
C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\christianl\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\christianl\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools

**Comment by AsgerPetersen** [comment]
@chleidersdorff it looks like you have configured QLR browser to a directory with more than 1000 sub items. Unfortunately the code has a bug which prevents the user from seeing the real error message. This is the line which throws an error:
```python
raise FileSystemRecursionException("File system is too big for this file system model", self.maxcount)
```
Please check that the root directory you have configured for the QLR browser is correct. If possible do not point to very large directory trees as the QLR browser freezes QGIS startup while reading the tree.

If you really need to point to a tree larger than 1000 items then you can raise the limit by adding an Integer parameter called `maxFileSystemObjects` in the advanced settings for QlrBrowser. 

![image](https://user-images.githubusercontent.com/1392735/67199333-5170c380-f401-11e9-80f1-cf9bc3dbaacb.png)

**Comment by AsgerPetersen** [comment]
We should fix the code so that `FileSystemRecursionException` is derived from `BaseException`
