### ISSUE TITLE
File system is too big for this file system model

### ISSUE THREAD

**Issue by ChrisFranklin666** [Septima/qgis-qlrbrowser#83]
This was working yesterday, now its broken, can we remove the limit for folders?

QlrBrowser.core.filesystemmodel.FileSystemRecursionException: 'File system is too big for this file system model' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python\qgis\utils.py", line 360, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/chrifran/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\qlrbrowser.py", line 174, in initGui
    self.dockwidget.addRootPath(self.settings.value("baseDirectory"))
  File "C:/Users/chrifran/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\ui\dockwidget.py", line 99, in addRootPath
    fs.setRootPath(path)
  File "C:/Users/chrifran/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\core\filesystemmodel.py", line 27, in setRootPath
    self.update()
  File "C:/Users/chrifran/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\core\filesystemmodel.py", line 30, in update
    self.rootitem = FileSystemItem(self.rootpath, True, FileSystemRecursionCounter(self.settings), namingregex=self.namingregex())
  File "C:/Users/chrifran/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\core\filesystemmodel.py", line 78, in __init__
    self.children.append(FileSystemItem(finfo, recurse, recursion_counter, self.namingregex))
  File "C:/Users/chrifran/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\core\filesystemmodel.py", line 78, in __init__
    self.children.append(FileSystemItem(finfo, recurse, recursion_counter, self.namingregex))
  File "C:/Users/chrifran/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\core\filesystemmodel.py", line 78, in __init__
    self.children.append(FileSystemItem(finfo, recurse, recursion_counter, self.namingregex))
  File "C:/Users/chrifran/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\core\filesystemmodel.py", line 60, in __init__
    recursion_counter.increment()
  File "C:/Users/chrifran/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QlrBrowser\core\filesystemmodel.py", line 185, in increment
    raise FileSystemRecursionException("File system is too big for this file system model", self.maxcount)
QlrBrowser.core.filesystemmodel.FileSystemRecursionException: 'File system is too big for this file system model'

**Comment by AsgerPetersen** [comment]
Hi @ChrisFranklin666 

Thank you for raising this. The limit to the number of objects read from the file system was introduced to prevent QGIS from locking up for a long period of time if the user accidentally set the search path to for instance `C:\`. In that case the qlr-browser will block QGIS while it reads the entire C-drive which may take a long time. See #27 for an example of this problem. To avoid this the qlr-browser stops traversing the file system if more than 1000 objects have been read.

The best solution to this problem would be asynchronous file system traversal like described in  #31. However we have not seen a lot of interest in getting this implemented. 

A less elegant work around would be raising the limit on your system. Open the python console (Plugins -> Python Console) and enter:
```python
s = QgsSettings()
s.setValue("plugins/QlrBrowser/maxFileSystemObjects", 10000)
```
This would set the limit to 10000 objects (where the default is 1000).

**Comment by MieWinstrup** [comment]
With asyn load in [version 3.0.0](https://github.com/Septima/qgis-qlrbrowser/releases/tag/v.3.0.0), the number is increased to 5000
